// ===== 示例数据 =====
const INTENT_CONFIG = {
  writing:  { label: '写作',    emoji: '✍️', color: '#7C6FFF', bg: '#F0EEFF' },
  decision: { label: '决策',    emoji: '⚖️', color: '#FF7C52', bg: '#FFF0EC' },
  learning: { label: '学习',    emoji: '📖', color: '#29B67C', bg: '#E8FAF3' },
  sharing:  { label: '分享',    emoji: '📡', color: '#F0A500', bg: '#FFF8E6' },
  later:    { label: '以后再说', emoji: '🌀', color: '#8D8BA7', bg: '#F3F3F8' },
};

const SAMPLE_ITEMS = [
  {
    id: 's1',
    title: '尼尔森十大可用性原则',
    content: 'https://www.nngroup.com/articles/ten-usability-heuristics/\n\n系统可见性、现实世界匹配、用户控制与自由、一致性与标准、错误预防……是评估任何界面的基础框架。',
    summary: '评估界面可用性的10条黄金法则，适合用于设计评审和竞品分析。',
    intent: 'writing',
    nextStep: '下篇文章用这个框架分析竞品 App',
    tags: ['设计', 'UX'],
    createdAt: Date.now() - 8 * 86400000,
    aiProcessed: true,
  },
  {
    id: 's2',
    title: '费曼学习法',
    content: '用最简单的语言向一个不懂的人解释某个概念，如果解释不清楚，说明你自己还没真正理解。学习的最高境界是能够教会别人。',
    summary: '通过"向小白解释"来检验自己是否真正掌握了某个知识点。',
    intent: 'sharing',
    nextStep: '整理成一条 Twitter 线程分享',
    tags: ['方法论', '学习'],
    createdAt: Date.now() - 5 * 86400000,
    aiProcessed: true,
  },
  {
    id: 's3',
    title: 'AARRR 增长模型笔记',
    content: 'Acquisition 获取 → Activation 激活 → Retention 留存 → Revenue 变现 → Referral 传播。每个阶段都需要独立策略和指标，不能混在一起分析。',
    summary: '海盗指标框架，用于拆解产品增长的5个关键环节。',
    intent: 'decision',
    nextStep: '套用到新项目的 Q2 增长策略 PPT 里',
    tags: ['产品', '增长'],
    createdAt: Date.now() - 12 * 86400000,
    aiProcessed: true,
  },
  {
    id: 's4',
    title: '非暴力沟通四步法',
    content: '1. 观察（不评判）2. 感受（区分感受和想法）3. 需要（感受背后的需要）4. 请求（具体可行的请求）\n用这个框架表达：「当我看到…，我感到…，因为我需要…，你愿意…吗？」',
    summary: '用观察-感受-需要-请求四步，代替评判和指责，实现有效沟通。',
    intent: 'learning',
    nextStep: '在下次一对一谈话里试用一次',
    tags: ['沟通', '阅读'],
    createdAt: Date.now() - 3 * 86400000,
    aiProcessed: true,
  },
  {
    id: 's5',
    title: '双钻设计模型',
    content: '发现（广泛研究）→ 定义（聚焦问题）→ 开发（探索方案）→ 交付（落地最优）。先发散再收敛，做对的事，再把事做对。',
    summary: '两次发散-收敛的设计流程，确保先找对问题再给解法。',
    intent: 'writing',
    nextStep: '写进团队的设计流程规范文档',
    tags: ['设计', '方法论'],
    createdAt: Date.now() - 15 * 86400000,
    aiProcessed: true,
  },
  {
    id: 's6',
    title: '一个关于间歇性断食的链接',
    content: 'https://example.com/intermittent-fasting\n\n看到有人推荐 16:8 方案，说对专注力有帮助。不知道适不适合自己。',
    summary: '',
    intent: 'later',
    nextStep: '',
    tags: [],
    createdAt: Date.now() - 1 * 86400000,
    aiProcessed: false,
  },
  {
    id: 's7',
    title: 'Promise.all 并行请求技巧',
    content: '多个无依赖的异步操作用 Promise.all 并行执行，而不是 await 嵌套。\n```js\nconst [user, posts] = await Promise.all([fetchUser(id), fetchPosts(id)]);\n```',
    summary: '用 Promise.all 代替串行 await，大幅减少等待时间。',
    intent: 'learning',
    nextStep: '重构项目里那几处瀑布式请求',
    tags: ['技术', '前端'],
    createdAt: Date.now() - 6 * 86400000,
    aiProcessed: true,
  },
  {
    id: 's8',
    title: '用户访谈5大禁忌',
    content: '❌ 问假设性场景 ❌ 问封闭式问题 ❌ 引导性提问 ❌ 一次问多个问题 ❌ 问"你会用这个功能吗"\n✅ 正确做法：只问过去真实发生的行为。',
    summary: '避免五类常见的访谈错误，聚焦用户真实行为而非假设意愿。',
    intent: 'sharing',
    nextStep: '做成一页纸 Cheatsheet 发给新同事',
    tags: ['产品', '用研'],
    createdAt: Date.now() - 20 * 86400000,
    aiProcessed: true,
  },
];
